### ISSUE TITLE
Incomprehensible error for the user when authorizing the card

### ISSUE THREAD

**Issue by Kolyall** [ITECOMMPAY/paymentpage-sdk-android#5]
`com.ecommpay:paymentpage-sdk-android:1.12.3`

Incomprehensible error for the user when authorizing the card

![Image from iOS](https://user-images.githubusercontent.com/3495165/154924061-f5cf710b-43c5-4148-8ff4-251ada2c07cf.jpg)

**Comment by AlexeyKhrameev** [comment]
Hello
Can u provide more information about payment?

**Comment by AlexeyKhrameev** [comment]
if u have the same problem at last version, please reopen issue
